#!/bin/bash
# Author - Tom Schumm <phong@phong.org>
#
# Generates variables for the various colors offered by the terminal
#
# This first checks to see if there is cached information about the
# colors for the terminal in ~/.bashkit/colors/$TERM, and if so, gets it from
# there, otherwise, it uses tput to get that information and
# caches it in that file.  If the file is bogus, delete it and this
# will regenerate it.
#
# May require the installation of the ncurses-term package on debian/ubunutu
# based distros.

function gencolors {
    local X=0
    local COLORNAME

    COLOR_NAMES="BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE"
    COLOR_CLEAR=`tput sgr0 2> /dev/null`
    NUM_COLORS=`tput colors 2> /dev/null`
    if [ "$NUM_COLORS" == "" ]; then
        NUM_COLORS=0
    fi
    if [ $? -gt 0 ] || [ $NUM_COLORS -lt 8 ]; then
        # Aw, terminfo is broke or something
        for COLORNAME in $COLOR_NAMES ; do
            eval "F_D${COLORNAME}=''"
            eval "F_L${COLORNAME}=''"
            eval "B_D${COLORNAME}=''"
            eval "B_L${COLORNAME}=''"
        done
    elif [ $NUM_COLORS -ge 16 ]; then
        # We have a glorious pretty terminal
        for COLORNAME in $COLOR_NAMES ; do
            eval "F_D${COLORNAME}=\`tput setaf $X\`"
            eval "F_L${COLORNAME}=\`tput setaf $(($X+8))\`"
            eval "B_D${COLORNAME}=\`tput setab $X\`"
            eval "B_L${COLORNAME}=\`tput setab $(($X+8))\`"
            X=$(($X+1))
        done
        for (( X=0; X<$NUM_COLORS; X++ )); do
            COLORNAME=`printf "0x%02x" $X`
            eval "F_${COLORNAME}=\`tput setaf $X\`"
            eval "B_${COLORNAME}=\`tput setab $X\`"
        done
        return 0
    else
        # Make due with fewer than 16 real colors
        for COLORNAME in $COLOR_NAMES ; do
            # add a case for a terminal that doesn't support the bold attribute
            eval "F_D${COLORNAME}=\`echo -e \"sgr0\nsetaf $X\"|tput -S $X\`"
            eval "F_L${COLORNAME}=\`echo -e \"setaf $X\nbold\"|tput -S\`"
            eval "B_D${COLORNAME}=\`tput setab $X\`"
            eval "B_L${COLORNAME}=\$B_D${COLORNAME}"
            # The following is necessary because terminfo for cygwin isn't quite right
            if [ "$TERM" = "cygwin" ] || [ "$TERM" = "putty" ] || [ "$TERM" = "rxvt" ]; then
                eval "B_L${COLORNAME}=\${B_L${COLORNAME}%%m}\;5m"
            fi
            X=$(($X+1))
        done
        return 0
    fi
    if [ $TERM = "dumb" ]; then return 0; fi
    return 1
}

function savecolors {
    local FILE=~/.bashkit/colors/$TERM
    local COLORNAME
    local PREF

    [ ! -e ~/.bashkit/colors ] && mkdir ~/.bashkit/colors
    cat > "$FILE" <<COMMENT
# Color information for $TERM

COLOR_NAMES="$COLOR_NAMES"
COLOR_CLEAR='$COLOR_CLEAR'
NUM_COLORS='$NUM_COLORS'
COMMENT
    for COLORNAME in $COLOR_NAMES ; do
        for PREF in F_D F_L B_D B_L ; do
            eval "echo $PREF$COLORNAME=\'\${$PREF$COLORNAME}\' >> $FILE"
        done
    done
    for (( X=0; X<$NUM_COLORS; X++ )); do
        COLORNAME=`printf "0x%02x" $X`
        eval "echo F_${COLORNAME}=\'\${F_$COLORNAME}\' >> $FILE"
        eval "echo B_${COLORNAME}=\'\${B_$COLORNAME}\' >> $FILE"
    done
}

if [ -f ~/.bashkit/colors/$TERM ]; then
    . ~/.bashkit/colors/$TERM
else
    if gencolors; then savecolors; fi
fi

unset gencolors
unset savecolors
