#!/bin/bash
# gencolors.sh (bash)
# Generates variables for the various colors offered by the terminal
# (C) 2003-2010 Thomas Schumm (visit http://www.phong.org)
#
# This first checks to see if there is cached information about the
# colors for the terminal in ~/.env/colors/$TERM, and if so, gets it from
# there, otherwise, it uses tput to get that information and
# caches it in that file.  If the file is bogus, delete it and this
# will regenerate it.
#
# May require the installation of the ncurses-term package on debian/ubunutu
# based distros.

function gencolors {
    local X=0
    local COLORNAME

    COLOR_NAMES="BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE"
    COLOR_CLEAR=`tput sgr0 2> /dev/null`
    if [ $? -gt 0 ] || [ `tput colors 2> /dev/null` -lt 8 ]; then
        # Aw, terminfo is broke or something
        for COLORNAME in $COLOR_NAMES ; do
            eval "F_D${COLORNAME}=''"
            eval "F_L${COLORNAME}=''"
            eval "B_D${COLORNAME}=''"
            eval "B_L${COLORNAME}=''"
        done
    elif [ `tput colors` -ge 16 ]; then
        # We have a glorious pretty terminal
        for COLORNAME in $COLOR_NAMES ; do
            eval "F_D${COLORNAME}=\`tput setaf $X\`"
            eval "F_L${COLORNAME}=\`tput setaf $(($X+8))\`"
            eval "B_D${COLORNAME}=\`tput setab $X\`"
            eval "B_L${COLORNAME}=\`tput setab $(($X+8))\`"
            X=$(($X+1))
        done
        return 0
    else
        # Make due with fewer than 16 real colors
        for COLORNAME in $COLOR_NAMES ; do
            # add a case for a terminal that doesn't support the bold attribute
            eval "F_D${COLORNAME}=\`echo -e \"sgr0\nsetaf $X\"|tput -S $X\`"
            eval "F_L${COLORNAME}=\`echo -e \"setaf $X\nbold\"|tput -S\`"
            eval "B_D${COLORNAME}=\`tput setab $X\`"
            eval "B_L${COLORNAME}=\$B_D${COLORNAME}"
            # The following is necessary because terminfo for cygwin isn't quite right
            if [ "$TERM" = "cygwin" ] || [ "$TERM" = "putty" ] || [ "$TERM" = "rxvt" ]; then
                eval "B_L${COLORNAME}=\${B_L${COLORNAME}%%m}\;5m"
            fi
            X=$(($X+1))
        done
        return 0
    fi
    if [ $TERM = "dumb" ]; then return 0; fi
    return 1
}

function savecolors {
    local FILE=~/.env/colors/$TERM
    local COLORNAME
    local PREF

    [ ! -e ~/.env/colors ] && mkdir ~/.env/colors
    cat > "$FILE" <<COMMENT
# Color information for $TERM
# Generated by gencolors.sh (C) 2003-2010 Thomas Schumm
# http://www.phong.org

COLOR_NAMES="$COLOR_NAMES"
COLOR_CLEAR='$COLOR_CLEAR'
COMMENT
    for COLORNAME in $COLOR_NAMES ; do
        for PREF in F_D F_L B_D B_L ; do
            eval "echo $PREF$COLORNAME=\'\${$PREF$COLORNAME}\' >> $FILE"
        done
    done
}

if [ -f ~/.env/colors/$TERM ]; then
    . ~/.env/colors/$TERM
else
    if gencolors; then savecolors; fi
fi

unset gencolors
unset savecolors
